export const lightTheme = {
  BACKGROUND_COLOR: "#F7F1E9",

  MOVIE_CARD_INFO_BACKGROUND_COLOR: "#1F1F1FAA",
  MOVIE_CARD_INFO_TEXT_COLOR: "#FFFFFF",

  BUTTON_BACKGROUND_COLOR: "#1F1F1F",
  BUTTON_TEXT_COLOR: "#FFFFFF",

  TEXT_INPUT_BORDER_COLOR: "#1F1F1F",
};
